name: Ilk DevOps Otomasyonum

on: [push]

jobs:
  gorev_bir:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Buluttan Cek
        uses: actions/checkout@v3
        
      - name: Ä°lk Otomatik Test
        run: echo "Sihir gerceklesti! Otomasyon robotu calisiyor."
      
      - name: Sahte Guvenlik Taramasi
        run: |
          echo "Sistem guvenlik aciklari taraniyor..."
          sleep 3
          echo "Tarama temiz! Hicbir acik bulunamadi."
